name: auzure-deployment

on:
  push:
    branches: [ main ]

jobs:
  myjob:
    runs-on: [self-hosted]
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account list
