on: [push, pull_request]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Install Azure cli
      
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v1
      
      
