on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
   runs-on: windows-latest
   steps:
   - name: Sample Azure action
     with: # Set Azure credentials secret as an input
       credentials: ${{ secrets.AZURE_CREDENTIALS }}
     env: # Or as an environment variable
       credentials: ${{ secrets.AZURE_CREDENTIALS }}
