on: [push]
name: AzureResource

jobs:
 build-and-deploy:
    runs-on: [windows-latest]
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION }}
